-- CreateTable
CREATE TABLE "Program" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "school" TEXT NOT NULL,
    "officialPrice" REAL,
    "currentPromoPrice" REAL,
    "activeDiscount" REAL,
    "discountValidFrom" DATETIME,
    "discountValidTo" DATETIME,
    "enrollmentsTotal" INTEGER NOT NULL DEFAULT 0,
    "revenueTotal" REAL NOT NULL DEFAULT 0,
    "associatedCampaigns" TEXT,
    "conversionRate" REAL,
    "bestChannel" TEXT,
    "lastCampaign" TEXT,
    "duration" TEXT,
    "credits" INTEGER,
    "modality" TEXT,
    "convocationStart" TEXT,
    "subjectsOrModules" TEXT,
    "mainFocuses" TEXT,
    "careerOutcomes" TEXT,
    "targetProfile" TEXT,
    "valueProposition" TEXT,
    "mainCommercialArgs" TEXT,
    "validatedClaims" TEXT,
    "restrictions" TEXT,
    "bestMessages" TEXT,
    "bestCtas" TEXT,
    "winningApproaches" TEXT,
    "successCasesAi" TEXT,
    "futureRecommendations" TEXT,
    "teamObservations" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- AlterTable: add optional programId to Brief
ALTER TABLE "Brief" ADD COLUMN "programId" TEXT REFERENCES "Program"("id") ON DELETE SET NULL ON UPDATE CASCADE;
